-- Insert sample products
INSERT INTO products (name, description, price, category, image_url, stock_quantity, is_active)
VALUES 
  ('Fresh Duck Eggs (Dozen)', 'Premium fresh duck eggs from free-range ducks. Rich in nutrients and perfect for baking or cooking.', 6.99, 'Eggs', 'https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=400', 50, true),
  ('Organic Duck Eggs (Half Dozen)', 'Certified organic duck eggs from our pasture-raised ducks. No antibiotics or hormones.', 4.99, 'Eggs', 'https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=400', 30, true),
  ('Whole Roasted Duck', 'Premium whole duck, perfectly seasoned and ready to cook. Approximately 4-5 lbs.', 24.99, 'Meat', 'https://images.unsplash.com/photo-1544440892-77831c00c452?w=400', 15, true),
  ('Duck Breast Fillets', 'Premium duck breast fillets, perfect for grilling or pan-searing. Sold in pairs.', 18.99, 'Meat', 'https://images.unsplash.com/photo-1544440892-77831c00c452?w=400', 25, true),
  ('Duck Leg Quarters', 'Tender duck leg quarters, great for braising or slow cooking. Pack of 2.', 12.99, 'Meat', 'https://images.unsplash.com/photo-1544440892-77831c00c452?w=400', 20, true),
  ('Premium Duck Fat', 'Pure rendered duck fat, perfect for roasting potatoes or cooking. 16oz jar.', 8.99, 'Specialty', 'https://images.unsplash.com/photo-1556909045-2a2483435c6e?w=400', 40, true);

-- Insert sample blog posts
INSERT INTO blog_posts (title, slug, content, excerpt, image_url, author_id, is_published)
VALUES 
  ('The Benefits of Duck Eggs', 'benefits-of-duck-eggs', 'Duck eggs are a nutritional powerhouse that many people haven''t discovered yet. Compared to chicken eggs, duck eggs are larger, richer, and contain more protein and healthy fats. They''re also an excellent source of selenium, vitamin B12, and choline. For bakers, duck eggs are a secret weapon - their higher fat content and protein levels create fluffier cakes and more tender pastries. Our free-range ducks produce eggs that are not only delicious but also more sustainable than factory-farmed alternatives.', 'Discover why duck eggs are becoming the preferred choice for health-conscious consumers and professional chefs alike.', 'https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=600', '1', true),
  ('Farm-to-Table: Our Sustainable Practices', 'sustainable-farming-practices', 'At Modern Agro, sustainability isn''t just a buzzword - it''s the foundation of everything we do. Our ducks roam freely on our 50-acre farm, eating a natural diet supplemented with locally-sourced grains. We use rotational grazing to keep our pastures healthy and productive, and our waste management system ensures that nothing goes to waste. Duck manure is composted and used to fertilize our fields, creating a closed-loop system that benefits both our animals and the environment. We''re proud to be certified organic and committed to practices that will keep our farm productive for generations to come.', 'Learn about our commitment to sustainable farming and how we''re working to protect the environment while producing the highest quality products.', 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600', '1', true);
